services:
  mongo:
    image: mongo:latest
    container_name: futures-ctp-rtn--mongodb
    restart: always
    ports:
      - "10001:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - futures-ctp-rtn:/data/db

volumes:
  futures-ctp-rtn:
