services:
  mongo:
    image: mongo:8
    container_name: futures-ctp
    restart: always
    ports:
      - "10001:27017"
    command:
      - mongod
      - --replSet
      - random_name_cluster
    volumes:
      - futures-ctp:/data/db

volumes:
  futures-ctp:
    name: 'mongo--futures-ctp'
